version: '3'
services:
  app:
    build: .
    container_name: express
    command: yarn dev
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/usr/app
    networks:
      - nginx

  db:
    image: postgres:alpine
    restart: always
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=express
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data

  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
