version: '3'
services:
  app:
    image: bfaa1999/typescript-base:latest
    container_name: app
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/usr/app
    command: npm run dev

  db:
    image: postgres:alpine
    restart: always
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
